apiVersion: v1
kind: Service
metadata:
  name:  witschey-rtp-service
  namespace: witschey
spec:
  type: NodePort
  selector:
    app: witschey-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000